name: Build and Deploy Firebase Application
# See more https://github.com/marketplace/actions/github-action-for-firebase

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      
      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies
        run: npm ci --silent

      - name: Build
        run: npm run build -ws --if-present

      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: front
          path: frontend/dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Pre deploy functions  
        run: npm i --package-lock-only
        working-directory: backend

      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: front
          path: frontend/dist

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          PROJECT_ID: wwcomed-super-hero
